const API_URL = "http://localhost:3000/api";

/* ===================== LOGIN ===================== */
async function login() {
    const email = document.getElementById("email").value;
        const password = document.getElementById("password").value;

            if (!email || !password) {
                    alert("Veuillez remplir tous les champs");
                            return;
                                }

                                    try {
                                            const res = await fetch(`${API_URL}/login`, {
                                                        method: "POST",
                                                                    headers: {
                                                                                    "Content-Type": "application/json"
                                                                                                },
                                                                                                            body: JSON.stringify({
                                                                                                                            email,
                                                                                                                                            password
                                                                                                                                                        })
                                                                                                                                                                });

                                                                                                                                                                        const data = await res.json();

                                                                                                                                                                                if (!res.ok) {
                                                                                                                                                                                            alert(data.message || "Erreur de connexion");
                                                                                                                                                                                                        return;
                                                                                                                                                                                                                }

                                                                                                                                                                                                                        // Stockage local
                                                                                                                                                                                                                                localStorage.setItem("connected", "true");
                                                                                                                                                                                                                                        localStorage.setItem("userId", data.user.id);
                                                                                                                                                                                                                                                localStorage.setItem("email", data.user.email);
                                                                                                                                                                                                                                                        localStorage.setItem("credits", data.user.credits);

                                                                                                                                                                                                                                                                window.location.href = "dashboard.html";

                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                            console.error(err);
                                                                                                                                                                                                                                                                                    alert("Impossible de contacter le serveur");
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                        /* ===================== REGISTER ===================== */
                                                                                                                                                                                                                                                                                        async function register() {
                                                                                                                                                                                                                                                                                            const email = document.getElementById("email").value;
                                                                                                                                                                                                                                                                                                const password = document.getElementById("password").value;

                                                                                                                                                                                                                                                                                                    if (!email || !password) {
                                                                                                                                                                                                                                                                                                            alert("Veuillez remplir tous les champs");
                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                    const res = await fetch(`${API_URL}/register`, {
                                                                                                                                                                                                                                                                                                                                                method: "POST",
                                                                                                                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                                                                                                                            "Content-Type": "application/json"
                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                    email,
                                                                                                                                                                                                                                                                                                                                                                                                                                    password
                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                const data = await res.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!res.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert(data.message || "Erreur lors de l'inscription");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alert("Compte créé avec succès !");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.location.href = "connexion.html";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Impossible de contacter le serveur");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                      