
                                                                                                                                                                                                                                               function login(){
                                                                                                                                                                                                                                                 localStorage.setItem("credits", "10");
                                                                                                                                                                                                                                                   window.location.href="dashboard.html";
                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                   function register(){
                                                                                                                                                                                                                                                     alert("Compte créé");
                                                                                                                                                                                                                                                       window.location.href="login.html";
                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                       